CAPITAL_PROFILES = {
    "SMALL_ACCOUNT": {
        "daily_start_capital": 2000.0,
        "option_stop_loss_pct": 0.20,
        "max_risk_per_trade_pct": 0.10,
        "min_contract_cost": 100.0,
        "preferred_max_contract_cost": 400.0,
        "max_contract_cost": 500.0,
        "aggressive_max_contract_cost": 750.0,
        "min_affordable_delta": 0.25,
        "max_active_trades": 1,
        "max_daily_entries": 3,
    },
    "GROWTH_ACCOUNT": {
        "daily_start_capital": 3000.0,
        "option_stop_loss_pct": 0.20,
        "max_risk_per_trade_pct": 0.10,
        "min_contract_cost": 150.0,
        "preferred_max_contract_cost": 900.0,
        "max_contract_cost": 1500.0,
        "aggressive_max_contract_cost": 2000.0,
        "min_affordable_delta": 0.25,
        "max_active_trades": 2,
        "max_daily_entries": 4,
    },
    "BEST_QUALITY": {
        "daily_start_capital": 25000.0,
        "option_stop_loss_pct": 0.20,
        "max_risk_per_trade_pct": 0.05,
        "min_contract_cost": 100.0,
        "preferred_max_contract_cost": 999999.0,
        "max_contract_cost": 999999.0,
        "aggressive_max_contract_cost": 999999.0,
        "min_affordable_delta": 0.20,
        "max_active_trades": 3,
        "max_daily_entries": 5,
    },
}