# tools/send_test_telegram_alert.py

from __future__ import annotations

import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

import requests
from dotenv import load_dotenv


def _load_toml(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}

    try:
        import tomllib  # Python 3.11+
    except ModuleNotFoundError:
        try:
            import tomli as tomllib  # type: ignore
        except ModuleNotFoundError:
            print(
                "tomllib/tomli not available. "
                "Use env vars TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID, "
                "or install tomli for Python < 3.11."
            )
            return {}

    with path.open("rb") as f:
        return tomllib.load(f)


def _get_telegram_config() -> tuple[str, str]:
    """
    Load Telegram config from:
    1. .env file
    2. Environment variables
    3. .streamlit/secrets.toml [telegram]
    """

    root = Path(__file__).resolve().parents[1]

    # Load .env from project root
    env_path = root / ".env"
    if env_path.exists():
        load_dotenv(env_path, override=True)

    bot_token = os.getenv("bot_token", "").strip()
    chat_id = os.getenv("chat_id", "").strip()
    print(f"Loaded Telegram config from .env or environment variables: bot_token={bot_token}, chat_id={chat_id}")

    if bot_token and chat_id:
        return bot_token, chat_id

    secrets_path = root / ".streamlit" / "secrets.toml"
    secrets = _load_toml(secrets_path)

    telegram = secrets.get("telegram", {}) if isinstance(secrets, dict) else {}

    bot_token = bot_token or str(telegram.get("bot_token", "")).strip()
    chat_id = chat_id or str(telegram.get("chat_id", "")).strip()

    if not bot_token:
        raise RuntimeError(
            "Missing Telegram bot token. Set TELEGRAM_BOT_TOKEN in .env "
            "or [telegram].bot_token in .streamlit/secrets.toml."
        )

    if not chat_id:
        raise RuntimeError(
            "Missing Telegram chat id. Set TELEGRAM_CHAT_ID in .env "
            "or [telegram].chat_id in .streamlit/secrets.toml."
        )

    return bot_token, chat_id


def send_test_alert() -> None:
    bot_token, chat_id = _get_telegram_config()

    message = (
        "✅ TEST ALERT\n\n"
        "Channel: Dravya Edge\n"
        "Purpose: Telegram channel delivery test\n"
        f"Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        "If you see this, the bot can post to the configured Telegram destination."
    )

    disclaimer_message = (
        "⚠️ DISCLAIMER\n\n"
        "Private Testing Disclaimer\n"

        "This channel is for personal testing and research only. Alerts are generated by an experimental trading scanner and are not financial advice or trade recommendations.\n"
        "Signals, prices, option contracts, P/L, and R-multiples may be delayed, incomplete, or wrong. Any real trade must be manually verified using live broker quotes and personal risk judgment.\n"
        "Options trading is high risk and can result in loss of capital. Past or paper results do not guarantee future performance.\n"
        "Current use: private E2E testing only between family. No public advisory service, no subscriber service, and no automated live trading.\n"
    )

    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"

    response = requests.post(
        url,
        json={
            "chat_id": chat_id,
            "text": message,
            "disable_web_page_preview": True,
        },
        timeout=15,
    )

    if response.ok:
        print("✅ Telegram test alert sent successfully.")
        print(f"Destination chat_id: {chat_id}")
        return

    print("❌ Telegram test alert failed.")
    print(f"HTTP status: {response.status_code}")
    print(response.text)
    response.raise_for_status()


if __name__ == "__main__":
    try:
        send_test_alert()
    except Exception as exc:
        print(f"❌ Error: {exc}")
        sys.exit(1)